/// XP Look
webFXTreeConfig.rootIcon		= "../../images/sysManage/folder.png";
webFXTreeConfig.openRootIcon	= "../../../images/sysManage/folder.png";
webFXTreeConfig.folderIcon		= "../../../images/sysManage/deptfolder.png";
webFXTreeConfig.openFolderIcon	= "../../../images/sysManage/deptfolder-open.png";
webFXTreeConfig.fileIcon		= "../../../images/sysManage/dept.png";
webFXTreeConfig.lMinusIcon		= "../../../images/sysManage/Lminus.png";
webFXTreeConfig.lPlusIcon		= "../../../images/sysManage/Lplus.png";
webFXTreeConfig.tMinusIcon		= "../../../images/sysManage/Tminus.png";
webFXTreeConfig.tPlusIcon		= "../../../images/sysManage/Tplus.png";
webFXTreeConfig.iIcon			= "../../../images/sysManage/I.png";
webFXTreeConfig.lIcon			= "../../../images/sysManage/L.png";
webFXTreeConfig.tIcon			= "../../../images/sysManage/T.png";